# Generated by Django 6.0.2 on 2026-03-27 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='close_reason',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='session',
            name='last_interaction_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='state_changed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='warning_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_known_state',
            field=models.CharField(choices=[('foreground', 'Foreground'), ('background', 'Background'), ('warning', 'Warning'), ('offline', 'Offline')], default='foreground', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('session_auto_ended', 'Session Auto Ended'), ('app_foregrounded', 'App Foregrounded'), ('app_backgrounded', 'App Backgrounded'), ('idle_warning', 'Idle Warning'), ('idle_warning_acknowledged', 'Idle Warning Acknowledged'), ('marked_offline', 'Marked Offline'), ('returned_online', 'Returned Online'), ('heartbeat', 'Heartbeat'), ('call_started', 'Call Started'), ('call_ended', 'Call Ended'), ('call_status_updated', 'Call Status Updated')], db_index=True, max_length=40)),
                ('app_state', models.CharField(blank=True, choices=[('foreground', 'Foreground'), ('background', 'Background'), ('warning', 'Warning'), ('offline', 'Offline')], max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='telecalling.call')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='telecalling.lead')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='telecalling.session')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['staff', 'created_at'], name='tc_act_staff_created'), models.Index(fields=['action_type', 'created_at'], name='tc_act_type_created')],
            },
        ),
    ]
