# Generated by Django 6.0.2 on 2026-03-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0002_session_close_reason_session_last_interaction_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Heavenection', max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('tax_identifier', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
