# Generated by Django 6.0.2 on 2026-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0003_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='compensation_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='target_hours_per_month',
            field=models.DecimalField(decimal_places=2, default=208, max_digits=6),
        ),
        migrations.AddField(
            model_name='staff',
            name='target_hours_per_week',
            field=models.DecimalField(decimal_places=2, default=48, max_digits=6),
        ),
        migrations.AddField(
            model_name='staff',
            name='weekly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
