# Generated by Django 6.0.2 on 2026-03-27 07:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0004_staff_compensation_type_staff_monthly_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('search_keywords', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_mandatory', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', '-published_at', 'title'),
            },
        ),
        migrations.AlterField(
            model_name='staffaction',
            name='action_type',
            field=models.CharField(choices=[('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('session_auto_ended', 'Session Auto Ended'), ('training_required_blocked', 'Training Required Blocked'), ('training_completed', 'Training Completed'), ('app_foregrounded', 'App Foregrounded'), ('app_backgrounded', 'App Backgrounded'), ('idle_warning', 'Idle Warning'), ('idle_warning_acknowledged', 'Idle Warning Acknowledged'), ('marked_offline', 'Marked Offline'), ('returned_online', 'Returned Online'), ('heartbeat', 'Heartbeat'), ('call_started', 'Call Started'), ('call_ended', 'Call Ended'), ('call_status_updated', 'Call Status Updated')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='TrainingCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_completions', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='telecalling.traininglesson')),
            ],
            options={
                'ordering': ('-completed_at',),
                'constraints': [models.UniqueConstraint(fields=('staff', 'lesson'), name='telecalling_unique_training_completion')],
            },
        ),
    ]
