# Generated by Django 6.0.2 on 2026-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0006_companyprofile_lead_queue_target_per_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='callback_window',
            field=models.CharField(blank=True, choices=[('noon', 'Noon'), ('evening', 'Evening'), ('night', 'Night')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='callback_window',
            field=models.CharField(blank=True, choices=[('noon', 'Noon'), ('evening', 'Evening'), ('night', 'Night')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('interested', 'Follow Up'), ('not_interested', 'Rejected'), ('no_answer', 'No Response'), ('call_back', 'Call Back'), ('converted', 'Converted'), ('invalid_short', 'Invalid Short')], db_index=True, default='started', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('interested', 'Follow Up'), ('not_interested', 'Rejected'), ('no_answer', 'No Response'), ('call_back', 'Call Back'), ('converted', 'Converted')], db_index=True, default='new', max_length=30),
        ),
    ]
