# Generated by Django 6.0.2 on 2026-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0007_call_callback_window_lead_callback_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='aadhar_photo',
            field=models.FileField(blank=True, null=True, upload_to='staff_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
