# Generated by Django 6.0.2 on 2026-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0008_staff_aadhar_number_staff_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='base_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='call_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salary',
            name='payout_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], db_index=True, default='monthly', max_length=20),
        ),
    ]
