# Generated by Django 6.0.2 on 2026-03-28 18:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0009_salary_base_pay_salary_bonus_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=40)),
                ('version_code', models.PositiveIntegerField(db_index=True, unique=True)),
                ('minimum_supported_version_code', models.PositiveIntegerField(default=0)),
                ('release_notes', models.TextField(blank=True)),
                ('apk_file', models.FileField(upload_to='app_releases/android/')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_app_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version_code', '-published_at'),
            },
        ),
    ]
