# Generated by Django 6.0.2 on 2026-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0010_alter_staff_role_apprelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='passbook_photo',
            field=models.FileField(blank=True, null=True, upload_to='staff_documents/passbook/'),
        ),
    ]
