# Generated by Django 6.0.2 on 2026-04-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0011_staff_passbook_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='verification_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='session',
            name='last_verified_call_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
