# Generated by Django 6.0.2 on 2026-04-02 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0012_call_is_verified_call_verification_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='auth_session_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
