# Generated by Django 6.0.2 on 2026-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0014_salarypaymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypaymenttransaction',
            name='payment_kind',
            field=models.CharField(choices=[('salary', 'Salary'), ('advance', 'Advance')], db_index=True, default='salary', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='weekly_payout_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='wednesday', max_length=12),
        ),
    ]
