# Generated by Django 6.0.2 on 2026-04-07 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0015_salarypaymenttransaction_payment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='referral_program_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='referral_required_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_staff_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qualified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], default='', max_length=30)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('payment_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earned_referral_reward', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-qualified_at', '-created_at'),
            },
        ),
    ]
