# Generated by Django 6.0.2 on 2026-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0017_referralsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='callback_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='callback_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
