# Generated by Django 6.0.2 on 2026-04-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0018_call_callback_date_lead_callback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hourly_call_bonus_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hourly_call_bonus_rate',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hourly_call_bonus_threshold',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
