# Generated by Django 6.0.2 on 2026-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0019_companyprofile_hourly_call_bonus_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='handover_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent to Client'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='handover_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
