# Generated by Django 6.0.2 on 2026-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0020_lead_handover_status_lead_handover_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsubmission',
            name='program_enabled_at_submit',
            field=models.BooleanField(default=True),
        ),
    ]
