# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telecalling", "0021_referralsubmission_program_enabled_at_submit"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="readd_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
