# Generated by Django 6.0.2 on 2026-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0026_referralsubmission_frozen_reward_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='auto_skipped_sync_issue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='sync_skip_reason',
            field=models.CharField(blank=True, choices=[('no_log_access', 'Auto skipped because no log access'), ('no_matching_log', 'Auto skipped because no matching call log'), ('log_read_failed', 'Auto skipped because log read failed')], db_index=True, default='', max_length=40),
        ),
    ]
