# Generated by Django 6.0.2 on 2026-05-05 10:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0027_call_auto_skipped_sync_issue_call_sync_skip_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], db_index=True, default='manual', max_length=20)),
                ('audience', models.CharField(choices=[('all_staff', 'All Staff'), ('single_staff', 'Single Staff')], db_index=True, default='all_staff', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_manual_close', models.BooleanField(default=True)),
                ('auto_dismiss_seconds', models.PositiveSmallIntegerField(default=6)),
                ('show_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('show_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_active', '-show_from', '-created_at'),
                'indexes': [models.Index(fields=['is_active', 'show_from'], name='tc_appnotif_active_from'), models.Index(fields=['audience', 'severity'], name='tc_appnotif_audience_sev')],
            },
        ),
    ]
