# Generated by Django 6.0.2 on 2026-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0028_appnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='lead_auto_delete_count',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='lead_auto_delete_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='lead_auto_delete_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='lead_auto_delete_last_run_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='lead_auto_delete_mode',
            field=models.CharField(choices=[('age_days', 'Delete by age'), ('oldest_count', 'Delete by oldest count')], default='age_days', max_length=20),
        ),
    ]
