# Generated by Django 6.0.2 on 2026-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0029_companyprofile_lead_auto_delete_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('interested', 'Follow Up'), ('expired_followup', 'Expired Follow Up'), ('not_interested', 'Rejected'), ('no_answer', 'No Response'), ('call_back', 'Call Back'), ('converted', 'Converted')], db_index=True, default='new', max_length=30),
        ),
    ]
