# Generated by Django 6.0.2 on 2026-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0035_companyprofile_followup_sla_gate_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='receives_new_leads',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
