# Generated by Django 6.0.2 on 2026-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0036_staff_receives_new_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='followup_moved_back_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
