# Generated by Django 6.0.2 on 2026-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0037_lead_followup_moved_back_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='loan_stage',
            field=models.CharField(blank=True, choices=[('office_review', 'Office Review'), ('documents_pending', 'Documents Pending'), ('verification', 'Verification'), ('approval', 'Approval'), ('disbursement', 'Disbursement'), ('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('interested', 'Interested'), ('expired_followup', 'Expired Follow Up'), ('not_interested', 'Rejected'), ('no_answer', 'No Response'), ('call_back', 'Call Back'), ('converted', 'Converted')], db_index=True, default='new', max_length=30),
        ),
    ]
